name: Build Oscript Docker Image

on:
  push:
    tags:
      - 'oscript_*'   # реагировать на теги, начинающиеся с executor_

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set environment variables
        run: |
          echo "DOCKER_REGISTRY_URL=${{ secrets.DOCKER_REGISTRY_URL }}" >> "$GITHUB_ENV"

      - name: Build and Push Docker image
        run: |
          export OSCRIPT_VERSION="${GITHUB_REF#refs/tags/oscript_}"
            echo "Собираем oscript версии ${OSCRIPT_VERSION}"
            ./src/build-oscript.sh
