name: Build Oscript Docker Image

on:
  push:
    tags:
      - 'oscript_*'   # реагировать на теги, начинающиеся с oscript_

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        run: |
          export OSCRIPT_VERSION="${GITHUB_REF#refs/tags/oscript_}"
          echo "Собираем oscript версии ${OSCRIPT_VERSION}"
          ./src/build-oscript.sh
