name: Build onec installer downloader Docker Image

on:
  push:
    tags:
      - 'onec-installer-downloader_*'   # реагировать на теги, начинающиеся с executor_

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
      DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Docker image
        run: |
          export ONEC_INSTALLER_DOWNLOADER_VERSION="${GITHUB_REF#refs/tags/onec-installer-downloader_}"
            echo "Собираем onec installer downloader версии ${ONEC_INSTALLER_DOWNLOADER_VERSION}"
            ./src/build-onec-installer-downloader.sh
